grafana:
  enabled: true
  fullnameOverride: grafana
  admin:
    existingSecret: ""
    user: admin
    password: ""

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - grafana.contoso.local
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - grafana.contoso.local
        secretName: grafana-tls
