grafana:
  enabled: true
  fullnameOverride: grafana
  admin:
    existingSecret: ""
    user: admin
    password: ""

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - grafana.contoso.local      
    path: /                        
    pathType: Prefix
    tls:
      - hosts:
          - grafana.contoso.local
        secretName: grafana-tls

  persistence:
    enabled: true
    size: 2Gi

  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 315
        revision: 4
        datasource: prometheus
      operations-overview:
        file: dashboards/operations-overview.json

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://contoso-monitoring-prometheus:9090
          access: proxy
          isDefault: true

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s    
    serviceMonitorSelector:
      matchLabels:
        monitoring: enabled
    podMonitorSelector:
      matchLabels:
        monitoring: enabled
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi


alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
