apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: contoso-monitoring
  labels:
    release: contoso-monitoring
    monitoring: enabled
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-repo-server-metrics
          - argocd-server-metrics
  endpoints:
    - port: http-metrics
      interval: 30s
      scrapeTimeout: 10s
