apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: contoso-monitoring
  labels:
    release: contoso-monitoring
    monitoring: enabled
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - application-controller
          - repo-server
          - server
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
