apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: contoso-monitoring
  labels:
    release: contoso-monitoring
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
