image:
  repository: ghcr.io/quovadis1212/contoso-app
  tag: "latest"

service:
  type: ClusterIP
  port: 3000
  invalid_line_here:

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  host: ""
